/**
 * @packageDocumentation
 * @module api.functional.expert_sub_categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IExpertCategory } from "./../../structures/expert_category";

/**
 * @summary 하위 전문 분야 목록 조회
 * @tag expert-categories
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param query 하위 전문 분야 필터링 조건
 * @return 하위 전문 분야 목록
 * @throw 404 NotFound
 * 
 * @controller ExpertSubCategoriesController.getList()
 * @path GET /expert-sub-categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection,
        query: IExpertCategory.ISub.ISearch
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path(query)
    );
}
export namespace getList
{
    export type Query = IExpertCategory.ISub.ISearch;
    export type Output = Array<IExpertCategory.ISub>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/expert-sub-categories";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(query: IExpertCategory.ISub.ISearch): string
    {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/expert-sub-categories${encoded.length ? `?${encoded}` : ""}`;;
    }
}

/**
 * @summary 상위 전문 분야 조회
 * @tag expert-categories
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param sub_category_id 하위 전문 분야 id
 * @return 상위 전문 분야 정보
 * @throw 404 NotFound
 * 
 * @controller ExpertSubCategoriesController.getOne()
 * @path GET /expert-sub-categories/:sub_category_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getOne
    (
        connection: IConnection,
        sub_category_id: string
    ): Promise<getOne.Output>
{
    return Fetcher.fetch
    (
        connection,
        getOne.ENCRYPTED,
        getOne.METHOD,
        getOne.path(sub_category_id)
    );
}
export namespace getOne
{
    export type Output = IExpertCategory.ISuper;

    export const METHOD = "GET" as const;
    export const PATH: string = "/expert-sub-categories/:sub_category_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(sub_category_id: string): string
    {
        return `/expert-sub-categories/${encodeURIComponent(sub_category_id ?? "null")}`;
    }
}