/**
 * @packageDocumentation
 * @module api.functional.users.re_agents.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { IREAgent } from "./../../../../structures/user/re_agent";

export * as properties from "./properties";

/**
 * @summary 공인중개사 내 정보 조회
 * @tag re-agents
 * @tag users
 * @return 공인중개사 내 정보
 * @throw 401 Unauthorized
 * @throw 403 Forbidden
 * 
 * @controller REAgentsController.get()
 * @path GET /users/re-agents/me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
    connection: IConnection,
): Promise<get.Output> {
    return !!connection.simulate
        ? get.simulate(
              connection,
          )
        : Fetcher.fetch(
              connection,
              get.ENCRYPTED,
              get.METHOD,
              get.path(),
          );
}
export namespace get {
    export type Output = IREAgent.IPrivate;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/re-agents/me";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/users/re-agents/me`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
    ): Promise<Output> => {
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}