/**
 * @packageDocumentation
 * @module api.functional.re_properties
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IREProperty } from "./../../structures/real_estate/re_property";
import type { IPaginatedResponse } from "./../../structures/common/pagination";

/**
 * @controller REPropertiesController.getList()
 * @path GET /re-properties
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection,
        query: IREProperty.ISearch
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path(query)
    );
}
export namespace getList
{
    export type Query = IREProperty.ISearch;
    export type Output = IPaginatedResponse<IREProperty>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/re-properties";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(query: IREProperty.ISearch): string
    {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/re-properties${encoded.length ? `?${encoded}` : ""}`;;
    }
}