/**
 * @packageDocumentation
 * @module api.functional.users.hs_providers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IBusinessUser } from "./../../../structures/user/business_user";
import type { IHSProvider } from "./../../../structures/user/hs_provider";

export * as me from "./me";

/**
 * @summary 생활서비스 전문가 목록 조회
 * @tag hs-providers
 * @tag users
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param query 필터링 기준
 * @return 생활서비스 제공자 목록
 * 
 * @controller HSProvidersController.getList()
 * @path GET /users/hs-providers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection,
        query: IBusinessUser.ISearch
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path(query)
    );
}
export namespace getList
{
    export type Query = IBusinessUser.ISearch;
    export type Output = IHSProvider.IPaginatedResponse;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/hs-providers";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(query: IBusinessUser.ISearch): string
    {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/users/hs-providers${encoded.length ? `?${encoded}` : ""}`;;
    }
}

/**
 * @summary 생활서비스 전문가 조회
 * @tag hs-providers
 * @tag users
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param provider_id 생활서비스 전문가 id
 * @return 생활서비스 제공자 정보
 * @throw 404 Not Found
 * 
 * @controller HSProvidersController.getOne()
 * @path GET /users/hs-providers/:provider_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getOne
    (
        connection: IConnection,
        provider_id: string
    ): Promise<getOne.Output>
{
    return Fetcher.fetch
    (
        connection,
        getOne.ENCRYPTED,
        getOne.METHOD,
        getOne.path(provider_id)
    );
}
export namespace getOne
{
    export type Output = IHSProvider;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/hs-providers/:provider_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(provider_id: string): string
    {
        return `/users/hs-providers/${encodeURIComponent(provider_id ?? "null")}`;
    }
}