/**
 * @packageDocumentation
 * @module api.functional.users.customers.me.zipzoong_care
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as requests from "./requests";