/**
 * @packageDocumentation
 * @module api.functional.zipzoong_care
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as request from "./request";