/**
 * @packageDocumentation
 * @module api.functional.users.customers.me.zipzoong_care.requests
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import { NestiaSimulator } from "./../../../../../../utils/NestiaSimulator";
import type { IZipzoongCareRequest } from "./../../../../../../structures/zipzoong_care_request";

/**
 * @summary 집중 케어 신청 목록 검색
 * @tag customers
 * @tag zipzoong-care
 * @param query 목록 검색 조건
 * @return 집중 케어 신청 목록
 * @throw 401 Unauthorized
 * @throw 403 Forbidden
 * 
 * @controller CustomersController.getList()
 * @path GET /users/customers/me/zipzoong-care/requests
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getList(
    connection: IConnection,
    query: IZipzoongCareRequest.ISearch,
): Promise<getList.Output> {
    return !!connection.simulate
        ? getList.simulate(
              connection,
              query,
          )
        : Fetcher.fetch(
              connection,
              getList.ENCRYPTED,
              getList.METHOD,
              getList.path(query),
          );
}
export namespace getList {
    export type Query = IZipzoongCareRequest.ISearch;
    export type Output = IZipzoongCareRequest.IPaginatedResponse;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/customers/me/zipzoong-care/requests";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (query: getList.Query): string => {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/users/customers/me/zipzoong-care/requests${encoded.length ? `?${encoded}` : ""}`;;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
        query: getList.Query,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path(query)
        });
        assert.query(() => typia.assert(query));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @summary 집중 케어 신청
 * @tag customers
 * @tag zipzoong-care
 * @param body 집중 케어 신청 정보
 * @throw 401 Unauthorized
 * @throw 403 Forbidden
 * 
 * @controller CustomersController.create()
 * @path POST /users/customers/me/zipzoong-care/requests
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
    connection: IConnection,
    body: IZipzoongCareRequest.ICreateRequest,
): Promise<void> {
    return !!connection.simulate
        ? create.simulate(
              connection,
              body,
          )
        : Fetcher.fetch(
              connection,
              create.ENCRYPTED,
              create.METHOD,
              create.path(),
              body,
              create.stringify,
          );
}
export namespace create {
    export type Input = IZipzoongCareRequest.ICreateRequest;

    export const METHOD = "POST" as const;
    export const PATH: string = "/users/customers/me/zipzoong-care/requests";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/users/customers/me/zipzoong-care/requests`;
    }
    export const simulate = async (
        connection: IConnection,
        body: create.Input,
    ): Promise<void> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path()
        });
        assert.body(() => typia.assert(body));
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}