/**
 * @packageDocumentation
 * @module api.functional.users.customers.me.zipzoong_care.requests
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IZipzoongCareRequest } from "./../../../../../../structures/zipzoong_care";
import type { IPaginatedResponse } from "./../../../../../../structures/common/pagination";

/**
 * @controller CustomersController.getList()
 * @path GET /users/customers/me/zipzoong-care/requests
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection,
        query: IZipzoongCareRequest.ISearch
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path(query)
    );
}
export namespace getList
{
    export type Query = IZipzoongCareRequest.ISearch;
    export type Output = IPaginatedResponse<IZipzoongCareRequest>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/customers/me/zipzoong-care/requests";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(query: IZipzoongCareRequest.ISearch): string
    {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/users/customers/me/zipzoong-care/requests${encoded.length ? `?${encoded}` : ""}`;;
    }
}