/**
 * @packageDocumentation
 * @module api.functional.auth.phone
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as request from "./request";
export * as verify from "./verify";