/**
 * @packageDocumentation
 * @module api.functional.auth.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { Authentication } from "./../../../structures/auth/auth";

/**
 * @summary 사용자 생성 API
 * @tag authentication
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param body 사용자 생성 정보
 * @returns void
 * @throw 401 Unauthorized
 * @throw 403 Forbidden
 * 
 * @controller AuthenticationController.create()
 * @path POST /auth/user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function create
    (
        connection: IConnection,
        body: Authentication.ICreateUser
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        create.ENCRYPTED,
        create.METHOD,
        create.path(),
        body,
        create.stringify
    );
}
export namespace create
{
    export type Input = Authentication.ICreateUser;

    export const METHOD = "POST" as const;
    export const PATH: string = "/auth/user";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/auth/user`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}