/**
 * @packageDocumentation
 * @module api.functional.upload
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as public_images from "./public_images";
export * as private_images from "./private_images";