/**
 * @packageDocumentation
 * @module api.functional.upload
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import { NestiaSimulator } from "./../../utils/NestiaSimulator";
import type { IUpload } from "./../../structures/upload";

/**
 * 리소스를 업로드하기 위한 presigned url을 얻기 위한 요청
 * 
 * @param resource_type resource type
 * @return url and presigned url
 * @throws 500 Internal Server Error
 * 
 * @controller UploadController.getUrls()
 * @path POST /upload
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUrls(
    connection: IConnection,
    body: IUpload.IInput,
): Promise<getUrls.Output> {
    return !!connection.simulate
        ? getUrls.simulate(
              connection,
              body,
          )
        : Fetcher.fetch(
              connection,
              getUrls.ENCRYPTED,
              getUrls.METHOD,
              getUrls.path(),
              body,
              getUrls.stringify,
          );
}
export namespace getUrls {
    export type Input = IUpload.IInput;
    export type Output = IUpload;

    export const METHOD = "POST" as const;
    export const PATH: string = "/upload";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/upload`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
        body: getUrls.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path()
        });
        assert.body(() => typia.assert(body));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}