/**
 * @packageDocumentation
 * @module api.functional.users.customers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { ICustomer } from "./../../../structures/user/customer";

export * as me from "./me";

/**
 * @summary 일반 고객 조회 API
 * @tag customers
 * @tag users
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param customer_id 일반 고객 id
 * @return 일반 고객 정보
 * @throw 404 Not Found
 * 
 * @controller CustomersController.getOne()
 * @path GET /users/customers/:customer_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getOne
    (
        connection: IConnection,
        customer_id: string
    ): Promise<getOne.Output>
{
    return Fetcher.fetch
    (
        connection,
        getOne.ENCRYPTED,
        getOne.METHOD,
        getOne.path(customer_id)
    );
}
export namespace getOne
{
    export type Output = ICustomer;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/customers/:customer_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(customer_id: string): string
    {
        return `/users/customers/${encodeURIComponent(customer_id ?? "null")}`;
    }
}