/**
 * @packageDocumentation
 * @module api.functional.business_rates.stats
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IBusinessRatesStats } from "./../../../structures/business_rates_stats";
import type { IPaginatedResponse } from "./../../../structures/common/pagination";

/**
 * @summary 사업자 별점 평균 목록 검색
 * @tag business_rates
 * @tag stats
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param query 별점 목록 검색 기준
 * @return 별점 평균 목록
 * 
 * @controller BusinessRatesStatsController.getList()
 * @path GET /business-rates/stats
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection,
        query: IBusinessRatesStats.ISearch
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path(query)
    );
}
export namespace getList
{
    export type Query = IBusinessRatesStats.ISearch;
    export type Output = IPaginatedResponse<IBusinessRatesStats>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/business-rates/stats";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(query: IBusinessRatesStats.ISearch): string
    {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/business-rates/stats${encoded.length ? `?${encoded}` : ""}`;;
    }
}