/**
 * @packageDocumentation
 * @module api.functional.sign_in.oauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { IAccessor } from "./../../../structures/user/accessor";

/**
 * Oauth2.0 로그인 요청
 * 
 * @summary Oauth 로그인 API
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param body oauth 로그인 요청 정보
 * @returns 로그인 토큰 정보
 * 
 * @controller AuthController.singIn()
 * @path POST /sign-in/oauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function singIn
    (
        connection: IConnection,
        body: IAccessor.ISignInBody
    ): Promise<singIn.Output>
{
    return Fetcher.fetch
    (
        connection,
        singIn.ENCRYPTED,
        singIn.METHOD,
        singIn.path(),
        body,
        singIn.stringify
    );
}
export namespace singIn
{
    export type Input = IAccessor.ISignInBody;
    export type Output = IAccessor;

    export const METHOD = "POST" as const;
    export const PATH: string = "/sign-in/oauth";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/sign-in/oauth`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}