/**
 * @packageDocumentation
 * @module api.functional.business_rate_categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IBusinessRateCategory } from "./../../structures/business_rate_category";

/**
 * @controller BusinessRateCategoriesController.getList()
 * @path GET /business-rate-categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection,
        query: IBusinessRateCategory.ISearch
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path(query)
    );
}
export namespace getList
{
    export type Query = IBusinessRateCategory.ISearch;
    export type Output = Array<IBusinessRateCategory>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/business-rate-categories";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(query: IBusinessRateCategory.ISearch): string
    {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/business-rate-categories${encoded.length ? `?${encoded}` : ""}`;;
    }
}