/**
 * @packageDocumentation
 * @module api.functional.re_property_categories.super
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IREPropertyCategory } from "./../../../structures/category/re_property";

/**
 * @summary 부동산 매물 상위 카테고리 목록 조회
 * @tag re-property-categories
 * @return 부동산 매물 상위 카테고리 목록
 * 
 * @controller REPropertySuperCategoriesController.getList()
 * @path GET /re-property-categories/super
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path()
    );
}
export namespace getList
{
    export type Output = Array<IREPropertyCategory.ISuper>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/re-property-categories/super";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/re-property-categories/super`;
    }
}

/**
 * @summary 부동산 매물 상위 카테고리 조회
 * @tag re-property-categories
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param super_category_id 부동산 매물 상위 카테고리 id
 * @return 부동산 매물 상위 카테고리
 * @throw 404 Not Found
 * 
 * @controller REPropertySuperCategoriesController.getOne()
 * @path GET /re-property-categories/super/:super_category_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getOne
    (
        connection: IConnection,
        super_category_id: string
    ): Promise<getOne.Output>
{
    return Fetcher.fetch
    (
        connection,
        getOne.ENCRYPTED,
        getOne.METHOD,
        getOne.path(super_category_id)
    );
}
export namespace getOne
{
    export type Output = IREPropertyCategory.ISuper;

    export const METHOD = "GET" as const;
    export const PATH: string = "/re-property-categories/super/:super_category_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(super_category_id: string): string
    {
        return `/re-property-categories/super/${encodeURIComponent(super_category_id ?? "null")}`;
    }
}