/**
 * @packageDocumentation
 * @module api.functional.re_property_categories.super
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import { NestiaSimulator } from "./../../../utils/NestiaSimulator";
import type { IREPropertyCategory } from "./../../../structures/category/re_property";

/**
 * @summary 부동산 매물 상위 카테고리 목록 조회
 * @tag re-properties
 * @tag categories
 * @return 부동산 매물 상위 카테고리 목록
 * 
 * @controller REPropertySuperCategoriesController.getList()
 * @path GET /re-property-categories/super
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getList(
    connection: IConnection,
): Promise<getList.Output> {
    return !!connection.simulate
        ? getList.simulate(
              connection,
          )
        : Fetcher.fetch(
              connection,
              getList.ENCRYPTED,
              getList.METHOD,
              getList.path(),
          );
}
export namespace getList {
    export type Output = Array<IREPropertyCategory.ISuper>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/re-property-categories/super";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (): string => {
        return `/re-property-categories/super`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
    ): Promise<Output> => {
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * @summary 부동산 매물 상위 카테고리 조회
 * @tag re-properties
 * @tag categories
 * @param super_category_id 부동산 매물 상위 카테고리 id
 * @return 부동산 매물 상위 카테고리
 * @throw 404 Not Found
 * 
 * @controller REPropertySuperCategoriesController.getOne()
 * @path GET /re-property-categories/super/:super_category_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getOne(
    connection: IConnection,
    super_category_id: string,
): Promise<getOne.Output> {
    return !!connection.simulate
        ? getOne.simulate(
              connection,
              super_category_id,
          )
        : Fetcher.fetch(
              connection,
              getOne.ENCRYPTED,
              getOne.METHOD,
              getOne.path(super_category_id),
          );
}
export namespace getOne {
    export type Output = IREPropertyCategory.ISuper;

    export const METHOD = "GET" as const;
    export const PATH: string = "/re-property-categories/super/:super_category_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export const path = (super_category_id: string): string => {
        return `/re-property-categories/super/${encodeURIComponent(super_category_id ?? "null")}`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Output =>
        typia.random<Output>(g);
    export const simulate = async (
        connection: IConnection,
        super_category_id: string,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METHOD,
            host: connection.host,
            path: path(super_category_id)
        });
        assert.param("super_category_id")("string")(() => typia.assert(super_category_id));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}