/**
 * @packageDocumentation
 * @module api.functional.agreements
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IAgreement } from "./../../structures/agreement";

/**
 * @summary 약관 조회
 * @tag agreements
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param query 약관 검색 조건
 * @return 약관 목록
 * 
 * @controller AgreementsController.getList()
 * @path GET /agreements
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getList
    (
        connection: IConnection,
        query: IAgreement.ISearch
    ): Promise<getList.Output>
{
    return Fetcher.fetch
    (
        connection,
        getList.ENCRYPTED,
        getList.METHOD,
        getList.path(query)
    );
}
export namespace getList
{
    export type Query = IAgreement.ISearch;
    export type Output = Array<IAgreement.IResponse>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/agreements";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(query: IAgreement.ISearch): string
    {
        const variables: Record<any, any> = query as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/agreements${encoded.length ? `?${encoded}` : ""}`;;
    }
}