/**
 * @packageDocumentation
 * @module api.functional.real_estate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
import typia from "typia";

import type { IRealEstateAgent } from "./../../structures/user/business/real_estate_agent";

/**
 * @summary 공인중개사 생성 API
 * @tag real_estates
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param body 공인중개사 생성 정보
 * @return 공인중개사 정보
 * 
 * @controller RealEstateController.create()
 * @path POST /real-estate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function create
    (
        connection: IConnection,
        body: IRealEstateAgent.ICreate
    ): Promise<create.Output>
{
    return Fetcher.fetch
    (
        connection,
        create.ENCRYPTED,
        create.METHOD,
        create.path(),
        body,
        create.stringify
    );
}
export namespace create
{
    export type Input = IRealEstateAgent.ICreate;
    export type Output = IRealEstateAgent.IUnVerified;

    export const METHOD = "POST" as const;
    export const PATH: string = "/real-estate";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/real-estate`;
    }
    export const stringify = (input: Input) => typia.assertStringify(input);
}

/**
 * @summary 공인중개사 조회 API
 * @tag real_estates
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param real_estate_id 공인중개사 ID
 * @return 공인중개사 정보
 * @throw 400 Real Estate Agent Not Found
 * @throw 412 Unprocessable Entity
 * 
 * @controller RealEstateController.find()
 * @path GET /real-estate/:real_estate_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function find
    (
        connection: IConnection,
        real_estate_id: string
    ): Promise<find.Output>
{
    return Fetcher.fetch
    (
        connection,
        find.ENCRYPTED,
        find.METHOD,
        find.path(real_estate_id)
    );
}
export namespace find
{
    export type Output = IRealEstateAgent;

    export const METHOD = "GET" as const;
    export const PATH: string = "/real-estate/:real_estate_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(real_estate_id: string): string
    {
        return `/real-estate/${encodeURIComponent(real_estate_id)}`;
    }
}