/**
 * @packageDocumentation
 * @module api.functional.users.customers.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { ICustomer } from "./../../../../structures/user/customer";

/**
 * @tag users
 * @return 일반 고객 내 정보
 * @throw 401 Unauthorized
 * @throw 403 Forbidden
 * 
 * @controller CustomersController.getMe()
 * @path GET /users/customers/me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getMe
    (
        connection: IConnection
    ): Promise<getMe.Output>
{
    return Fetcher.fetch
    (
        connection,
        getMe.ENCRYPTED,
        getMe.METHOD,
        getMe.path()
    );
}
export namespace getMe
{
    export type Output = ICustomer.IPrivate;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/customers/me";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/users/customers/me`;
    }
}