/**
 * @packageDocumentation
 * @module api.functional.re_property_categories.middle
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IREPropertyCategory } from "./../../../structures/category/re_property";

/**
 * @summary 부동산 매물 중위 카테고리 조회
 * @tag re-property-categories
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param middle_category_id 부동산 매물 중위 카테고리 id
 * @return 부동산 매물 중위 카테고리
 * @throw 404 Not Found
 * 
 * @controller REPropertyMiddleCategoriesController.getOne()
 * @path GET /re-property-categories/middle/:middle_category_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getOne
    (
        connection: IConnection,
        middle_category_id: string
    ): Promise<getOne.Output>
{
    return Fetcher.fetch
    (
        connection,
        getOne.ENCRYPTED,
        getOne.METHOD,
        getOne.path(middle_category_id)
    );
}
export namespace getOne
{
    export type Output = IREPropertyCategory.IMiddle;

    export const METHOD = "GET" as const;
    export const PATH: string = "/re-property-categories/middle/:middle_category_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(middle_category_id: string): string
    {
        return `/re-property-categories/middle/${encodeURIComponent(middle_category_id ?? "null")}`;
    }
}