/**
 * @packageDocumentation
 * @module api.functional.service_categories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as super from "./super";